[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
chainequity_factory = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
chainequity_governance = "BPFLoaderUpgradeab1e11111111111111111111111"
chainequity_token = "HmbTLCmaGvZhKnn1Zfa1JVnp7vkMV4DYVxPLWBVoN65L"
test_usdc = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[programs.localnet]
chainequity_factory = "S7psPXnjCLjqdhoWXVG78nniuCfGPwQaciq7TUZEL2p"
chainequity_governance = "CKL6Y6ma5nffMts5Q3fEyER9RoPHHGoxFnEYuLXvNWrd"
chainequity_token = "5H3QcvZsViboQzqnv2vLjqCNyCgQ4sx3UXmYgDihTmLV"
test_usdc = "28JkLhzXCQme5fFrAqoWwyJxSNiv71CMQcS5x4xCtqoX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-factory = "npx ts-node scripts/init-and-create-token.ts"
create-token = "npx ts-node scripts/create-token.ts"
seed-data = "npx ts-node scripts/seed-test-data.ts"
seed-demo = "npx ts-node scripts/seed-demo-data.ts"
